[features]
seeds = false
skip-lint = false
[programs.devnet]
myepicproject = "GiARCEmixpiQAxAfDRWTGS6MX26MqQ4gVppVt38YaaoW"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "/home/thiago/.config/solana/id.json"

[scripts]
test = "node tests/myepicproject.js"